services:
  frontend:
    build:
      context: ./Frontend-V2
      dockerfile: frontend.Dockerfile
    ports:
      - "$FRONTEND_PORT:5173"
    volumes:
      - "./Frontend-V2:/app"
      - "/app/node_modules"
    container_name: "ipWho_frontend"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: backend.Dockerfile
    ports:
      - "$BACKEND_PORT:5172"
    env_file:
      - ./Backend/.env
    container_name: "ipWho_backend"
    volumes:
      - "/app/node_modules"
      - "./Backend:/app"

  redis:
    image: redis
    container_name: "ipWho_redis"
    ports:
      - "6380:6379"
    command: redis-server --requirepass $REDIS_PASSWORD
