services:
  redis:
    image: redis
    ports:
      - "$REDIS_PORT:6379"
    container_name: "ipWho_redis_testing"

  frontend:
    build:
      context: ./Frontend-V2
      dockerfile: frontend.Dockerfile
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"
    container_name: "ipWho_frontend_testing"
    command: npm run build
    env_file:
      - $FRONTEND_ENV

  backend:
    build:
      context: ./Backend
      dockerfile: backend.Dockerfile
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    env_file:
      - $BACKEND_ENV
    container_name: "ipWho_backend_testing"
    volumes:
      - "/app/node_modules"
      - "$BACKEND_LOGS_LOCATION:/logs"
      - "$BACKEND_FILE_LOCATION:/app/mainFiles:ro"
    depends_on:
      - frontend
      - redis