export {meRouter} from './me/routes/meRoute.js'
export {ipRouter} from './ip/routes/ipRoute.js'
export {metricsRouter} from './metrics/routes/metricsRoute.js'
export {statusRouter} from './status/routes/statusRoute.js'
export {bulkRouter} from './bulk/routes/bulkRoute.js'