apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipwho-mainfiles-prod
  labels:
    type: ipWho-Mainfiles
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  nfs:
    server: # Can be changed to anything based on needs
    path: /mnt/nfs/ipWho_data/mainFiles
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipwho-backend-readonly-pvc
  namespace: ipwho
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: ipWho-Mainfiles