apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pod-pv
  namespace: ipwho
  labels:
    type: redis-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: # Can be changed to anything based on requirements
    path: /mnt/nfs/redis
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: ipwho
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: redis-nfs