name: CI Test
on: [push,workflow_dispatch]
jobs:
  backend-Test:
    runs-on: [self-hosted]
    steps:
      - name: Pull Code
        uses: actions/checkout@v4
      
      - name: Build Image and Run Containers
        run: docker compose -f docker-compose-test.yml --env-file /env/ipWho/.env up -d --build

      - name: Run test's
        run: docker exec -i ipWho_backend_testing bash -c "npm run test"
      
      - name: Stop Containers
        run: docker compose -f docker-compose-test.yml --env-file /env/ipWho/.env down